---
title: "GLMM Analysis"
author: "Irina"
date: "2026-06-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lme4)
library(lmerTest)
library(readxl)
```

```{r}
my_data <- read_excel("C:/Users/0cher/Documents/TMS_models/TMS_Master.xlsx", sheet = "Sheet1")

my_data$Error_binary <- as.numeric(my_data$Error_binary)
my_data$Frequency <- as.factor(my_data$Frequency)
my_data$pID <- as.factor(my_data$pID)
my_data$Region <- as.factor(my_data$Region)
my_data$Stimulus <- as.factor(my_data$Stimulus)
```

```{r}
model_errors <- glmer(Error_binary ~ Frequency + (1|pID) + (1|Region),
                      data = my_data,
                      family = binomial,
                      control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e5)))
summary(model_errors)
```

```{r}
model_full <- glmer(Error_binary ~ Frequency + Region + (1|pID) + (1|Stimulus),
                    data = my_data,
                    family = binomial,
                    control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e5)))
summary(model_full)
```